// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cywlogrmruycovtlasti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5d2xvZ3JtcnV5Y292dGxhc3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzA3MDUsImV4cCI6MjA2MTEwNjcwNX0.yzNI6JFHBHg9GM_oY5NvpYhWGa-mzuPbQ_pd5dFbt6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);